apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: cloudbox-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbox-app
  template:
    metadata:
      labels:
        app: cloudbox-app
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
